<a href="https://colab.research.google.com/github/PraveeshS/ML-project/blob/main/heartdiesease7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd
import seaborn as sns 
import numpy as np
from sklearn.model_selection import train_test_split

In [59]:
data=pd.read_csv('https://talentcocomedia.s3.amazonaws.com/ml-assets/heart-disease.csv')

In [ ]:
x=data.drop(['target'],axis=1)

In [ ]:
y=data['target']

In [ ]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((212, 13), (91, 13), (212,), (91,))

**LogisticRegression**

In [ ]:
from sklearn.linear_model import LogisticRegression
model_lr=LogisticRegression(penalty='l2',solver='newton-cg',C=5)

In [ ]:
model_lr.fit(x_train,y_train)

LogisticRegression(C=5, solver='newton-cg')

In [ ]:
y_predlr=model_lr.predict(x_test)
y_predlr

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1])

**Accuracy** **of** **Logistic** **Regression**

In [ ]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_predlr,y_test)
acc

0.8791208791208791

**KNeighborsClassifier**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neighbor = KNeighborsClassifier(n_neighbors=3)
neighbor.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_predkn=neighbor.predict(x_test)
y_predkn

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1])

In [ ]:
accu=accuracy_score(y_predkn,y_test)

**Accuracy of Kneighbor** **classifier**

In [ ]:
accu


0.6703296703296703

**DecisionTreeclassifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
decisionTree=DecisionTreeClassifier()
decisionTree.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_preddtc=decisionTree.predict(x_test)
y_preddtc

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0])

**Accuracy of DecisionTreeclassifier**

In [ ]:
accuradtc=accuracy_score(y_preddtc,y_test)
accuradtc

0.8021978021978022

### **LogisticRegression-GridSearchCV**

In [ ]:

from sklearn.model_selection import GridSearchCV
model = LogisticRegression(penalty ='l2')

val = list(np.arange(0.1,1,0.1))

parameters = {'solver':('newton-cg', 'liblinear','sag','saga'),'C':val}

clf_lr = GridSearchCV(model,parameters)
clf_lr.fit(x_train,y_train)
     

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means 

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6,
                               0.7000000000000001, 0.8, 0.9],
                         'solver': ('newton-cg', 'liblinear', 'sag', 'saga')})

In [ ]:
print(clf_lr.best_params_)

{'C': 0.2, 'solver': 'newton-cg'}


In [ ]:
test_pred = clf_lr.predict(x_test)


In [ ]:
accflr = accuracy_score(test_pred,y_test)
accflr

0.8791208791208791

### **KNeighbors-GridSearchCV**

In [60]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier()

val = list(np.arange(1,30, 1))

parameters = {'n_neighbors':val}

clf_knn = GridSearchCV(neigh, parameters)
clf_knn.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29]})

In [61]:
print(clf_knn.best_params_)

{'n_neighbors': 28}


In [62]:
kneighpred=clf_knn.predict(x_test)

In [63]:
accuflr=accuracy_score(kneighpred,y_test)
accuflr

0.7142857142857143

### **DecisionTreeClassifier - GridSearchCV**

In [64]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [65]:
clf = DecisionTreeClassifier(random_state=1024)

param_grid = {
              'max_features': ['auto', 'sqrt', 'log2'],
              'ccp_alpha': [0.1, .01, .001],
              'max_depth' : np.arange(5,10,1),
              'criterion' :['gini', 'entropy']
             }

clf_dtc = GridSearchCV(clf, param_grid=param_grid, cv=5, verbose=True)

clf_dtc.fit(x_train, y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits


/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1024),
             param_grid={'ccp_alpha': [0.1, 0.01, 0.001],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': array([5, 6, 7, 8, 9]),
                         'max_features': ['auto', 'sqrt', 'log2']},
             verbose=True)

In [66]:
print(clf_dtc.best_params_)

{'ccp_alpha': 0.01, 'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto'}


In [67]:
dtc_pred = clf_dtc.predict(x_test)

In [69]:
accuracy_dtc_gs = metrics.accuracy_score(y_test, dtc_pred)
accuracy_dtc_gs

0.8571428571428571

**Confusion Matrix for LogisticRegression**

In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_pred,y_test)

array([[29,  1],
       [10, 51]])

In [73]:
from sklearn.metrics import classification_report
print(classification_report(y_test,test_pred))


              precision    recall  f1-score   support

           0       0.97      0.74      0.84        39
           1       0.84      0.98      0.90        52

    accuracy                           0.88        91
   macro avg       0.90      0.86      0.87        91
weighted avg       0.89      0.88      0.88        91



**Confusion Matrix for KNeighbors**

In [76]:
from sklearn.metrics import confusion_matrix
confusion_matrix(kneighpred,y_test)


array([[21,  8],
       [18, 44]])

In [77]:
from sklearn.metrics import classification_report
print(classification_report(y_test,kneighpred))

              precision    recall  f1-score   support

           0       0.72      0.54      0.62        39
           1       0.71      0.85      0.77        52

    accuracy                           0.71        91
   macro avg       0.72      0.69      0.69        91
weighted avg       0.72      0.71      0.71        91



**Confusion Matrix for DecisionTree**

In [78]:
from sklearn.metrics import confusion_matrix
confusion_matrix(dtc_pred,y_test)

array([[28,  2],
       [11, 50]])

In [80]:
from sklearn.metrics import classification_report
print(classification_report(y_test,dtc_pred))

              precision    recall  f1-score   support

           0       0.93      0.72      0.81        39
           1       0.82      0.96      0.88        52

    accuracy                           0.86        91
   macro avg       0.88      0.84      0.85        91
weighted avg       0.87      0.86      0.85        91

